-- AlterTable
ALTER TABLE "PunchIn" ALTER COLUMN "punchInTime" DROP DEFAULT,
ALTER COLUMN "punchInTime" SET DATA TYPE TEXT,
ALTER COLUMN "punchInDate" DROP DEFAULT,
ALTER COLUMN "punchInDate" SET DATA TYPE TEXT;
